services:
  proxy:
    build: .docker/proxy
    depends_on:
      - adminer
      - server
      - web
    environment:
      WEB_PORT: 3000
  adminer:
    image: adminer
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: postgres
  server:
    build:
      dockerfile: applications/server/Dockerfile
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://sideline:sideline@postgres:5432/sideline
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT: https://sideline-preview.majksa.net/api
      API_PREFIX: /api
      FRONTEND_URL: ${BASE_URL}
      SERVER_URL: ${BASE_URL}/api
  bot:
    build:
      dockerfile: applications/bot/Dockerfile
    depends_on:
      - server
    environment:
      NODE_ENV: development
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
  web:
    build:
      dockerfile: applications/web/Dockerfile
    depends_on:
      - server
    environment:
      SERVER_URL: ${BASE_URL}/api
      PORT: 3000
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: sideline
      POSTGRES_PASSWORD: sideline
      POSTGRES_DB: sideline
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
