services:
  proxy:
    build: .docker/proxy
    environment:
      WEB_PORT: 3000
  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
  server:
    build:
      dockerfile: applications/server/Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://sideline:sideline@postgres:5432/sideline
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      FRONTEND_URL: ${BASE_URL}
      SERVER_URL: ${BASE_URL}/api
  bot:
    build:
      dockerfile: applications/bot/Dockerfile
    environment:
      NODE_ENV: development
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
  web:
    build:
      dockerfile: applications/web/Dockerfile
    environment:
      SERVER_URL: ${BASE_URL}/api
      PORT: 3000
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: sideline
      POSTGRES_PASSWORD: sideline
      POSTGRES_DB: sideline
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
